name: Deploy NagaraTrack-Lite to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend-pwa/**'
      - '.github/workflows/gh-pages.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend-pwa/package.json

      - name: Install dependencies
        working-directory: frontend-pwa
        run: npm ci

      - name: Build static application
        working-directory: frontend-pwa
        env:
          NODE_ENV: production
          VITE_STATIC_MODE: 'true'
        run: npm run build

      - name: Verify build output
        working-directory: frontend-pwa
        run: |
          echo "Build completed successfully"
          ls -la dist/
          echo "Data files:"
          ls -la dist/data/ || echo "No data directory found"
          echo "Assets:"
          ls -la dist/assets/ || echo "No assets directory found"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend-pwa/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Post-deployment notification
        run: |
          echo "🚀 NagaraTrack-Lite Demo deployed successfully!"
          echo "📍 URL: ${{ steps.deployment.outputs.page_url }}"
          echo "✅ Static mode enabled for GitHub Pages compatibility"